version: "3.9"

networks:
  ugh-lan:
    driver: bridge

services:
  ugh-db:
    build:
      context: .
      dockerfile: db.dockerfile
    volumes:
      - "./files/db-data:/var/lib/mysql"
    networks:
      - ugh-lan

  ugh-server:
    image: "adoptopenjdk/openjdk11"
    volumes:
      - "./files/server-data:/files"
    working_dir: "/files"
    networks:
      - ugh-lan
    ports:
      - "8080:8080"
    command: "sh -c 'sleep 30; java -jar server.jar'"# wait until db comes online
