spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: username
    password: password

project:
  description: "server for Umgebindehaus server-project"

server:
  error:
    include-message: always