spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/ugh
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: mariadb
  jpa:
    hibernate:
      ddl-auto: update

project:
  description: "server for Umgebindehaus server-project"
