spring:
  datasource:
    url: jdbc:mariadb://ugh-db:3306/Umgebindehaus
    driver-class-name: org.mariadb.jdbc.Driver
    username: 'umgebindehaus'
    password: '*insecure*'
  jpa:
    hibernate:
      ddl-auto: update

project:
  description: "server for Umgebindehaus server-project"
